### ISSUE TITLE
Typo in Travic CI "install" command

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [google/auto#241]
There's a typo in .travis.yml: "build.pom.xml" instead of "build-pom.xml". So the "install" command always fails. See error message for example here:
https://travis-ci.org/google/auto/jobs/63261133#L96

But because of the --fail-never option Maven ignores the failure.

**Comment by cgruber** [comment]
Fixed in #304

**Comment by arend-von-reinersdorff** [comment]
The filename is now correct.
But the install build step still fails, now with a different error:
https://travis-ci.org/google/auto/jobs/120990260#L137

I would suggest removing the "--fail-never" argument as it hides the build errors.
