### ISSUE TITLE
Memoized extension not picking up error-prone's `@LazyInit` annotations on the classpath

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#427]
Since `@Memoized` results in non-final fields, it can't be used in `@Immutable`-annotated classes. error-prone does have support for `@LazyInit` on fields like this though, would it be possible to have some sort of opt-in mechanism and generate these annotations with the fields?

**Comment by ronshapiro** [comment]
It should be doing that: https://github.com/google/auto/blob/57dfad360306619a820e6aae4a14a1aa67c29299/value/src/main/java/com/google/auto/value/extension/memoized/MemoizeExtension.java#L352

Are you not seeing it happen that way?

**Comment by tbroyer** [comment]
@ronshapiro AFAICT it hasn't been released. The commit is from November and the last release on Central is from October: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.auto.value%22%20AND%20a%3A%22auto-value%22

[GitHub releases page](https://github.com/google/auto/releases) says there's been a 1.4-rc-2 release (and there's a tag for it) that should contain the commit but it's apparently not on Central.

**Comment by ronshapiro** [comment]
That's weird, I do see it here: https://oss.sonatype.org/content/repositories/public/com/google/auto/value/auto-value/1.4-rc2/

**Comment by tbroyer** [comment]
It has apparently not been sync'd from OSSRH to Central: https://repo1.maven.org/maven2/com/google/auto/value/auto-value/  
Contact Sonatype?

**Comment by hzsweers** [comment]
Yeah I'm using -rc2 as well and it still wasn't showing up (haven't had maven issues). I'll tinker a bit more later today

**Comment by hzsweers** [comment]
I still can't get this to work for some reason

**Comment by eamonnmcmanus** [comment]
I assume this is fixed with AutoValue 1.4. Please let me know if not and I will reopen.

**Comment by hzsweers** [comment]
Yes I still see this issue on 1.4 :/. The LazyInit annotations never get added. I'll try to put together a repro case

**Comment by hzsweers** [comment]
Repro case: https://github.com/hzsweers/json-serialization-benchmarking/tree/z/errorProneAnnotations

Steps:
- Clone and check out the `z/errorProneAnnotations` branch
- `./gradlew compileJava`
- The class using `@Memoized` is `FriendAV.java`, for its `toString()` and `hashCode()` impls.
- Look at the top level generated `AutoValue_FriendAV` class (which is where the memoized extension functionality gets generated) and observe there's no `@LazyInit` annotations present on the memoized fields, even though I've ensured error prone annotations are available on the compile/apt/compileOnly classpaths.
